spring:
  flyway:
    enabled: false

  h2:
    console:
      enabled: true
  # 数据源配置
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:datajpa
      username: sa
      password: mypass
      minimum-idle: 8
      maximum-pool-size: 32
      auto-commit: true
      idle-timeout: 120000
      pool-name: HikariCP
      max-lifetime: 600000
      connection-timeout: 30000

  # jpa 配置
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

