spring:
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
  # 数据源配置
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:datajpa
      username: sa
      password: mypass

  # jpa 配置
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop